### ISSUE TITLE
Simplify number of actions needed to add a servant

### ISSUE THREAD

**Issue by enshael** [TohnoCoding/fgochecklist#1]
It might be simplier for users if the modal screen asking for the NP level is removed.

Alternative ux that I can think of:
- Click on the portrait to add NP1
- Show +/-/x buttons to Add/Subtract/Uncheck the servant
    - These can be shown either on hover (will be troublesome on mobile if done incorrectly) or permanently beneath the portraits

**Comment by TohnoCoding** [comment]
That's what Fast Mode is for. Once Fast Mode is activated you can just continuously click/tap on units to check/increase any given unit, looping back to unchecked after NP5 (on desktop, right-clicking does the same but backwards).

**Comment by enshael** [comment]
Oh! I didn't notice the checkbox when I tried it out. Sorry 🙈
