### ISSUE TITLE
Counting machine broke

### ISSUE THREAD

**Issue by Ace-Stargale** [TohnoCoding/fgochecklist#12]
<img width="1101" alt="Screenshot 2024-09-12 at 9 16 23 AM" src="https://github.com/user-attachments/assets/41e6d581-43ca-45fd-920a-284bddbfbe86">

Stats are broken for some reason. Actual interactive functionalities are all working, but the counts on the sides of how many of a given class+rarity you have shat themselves.

Additional thing I just noticed: Only broken when split up by class, the merged lists work as normal. I have Hide JP Servants, Mash is 4*, and Fast Mode on, if that helps.

**Comment by TohnoCoding** [comment]
Yep, I just realized this today and I'm working on it. Sit tight!

**Comment by TohnoCoding** [comment]
Statistics are now fixed regardless of whether Class Mode is active or not. Enjoy!

**Comment by TohnoCoding** [comment]
Statistics are now fixed regardless of whether Class Mode is active or not. Enjoy!
