### ISSUE TITLE
Checking Ptolemaios as "Owned" results in Wandjina being triggered as "Owned", and vice versa when unchecked + NP levels

### ISSUE THREAD

**Issue by PastMemories** [TohnoCoding/fgochecklist#27]
As stated by the title, seems to be an oddly niche bug when it comes to both Wandjina and Ptolemy. Anything that you do to Ptolemy is reflected to Wandjina and the same happens if you modify Wandjina in any way, it'll be reflected back to Ptolemy, be it checking either as owned or unowned, changing NP levels, even the wishlist stuff. Been a thing since months ago that I even logged in to my unused github account just to finally make an issue report. Hopefully this isn't too complicated of an issue to fix.

**Comment by TohnoCoding** [comment]
You're totally right -- there was a typo in their internal IDs that was triggering both to change whenever either was being affected. It's been fixed now by commit f9a84d679c4bc6dddf06664c38b5215868078831, so I'll be closing the issue. Thanks for letting me know!
